### ISSUE TITLE
Invalid API key or Invalid Hashes

### ISSUE THREAD

**Issue by Qian-Han** [ArtemKushnerov/az#6]
Hi,

I have already applied for an valid API key also use the script and lastest csv AndroZoo provided, however, it always returns invalid API key or invalid hashes. Could I know why it happened?

Thank you!

Such as this: https://androzoo.uni.lu/api/download?apikey=${API KEY}&sha256=${00008E0B8F27CFCDFA2A73A45A4450B0D5255F63C8B5AE407AEEF0DEA9842174}

**Comment by ArtemKushnerov** [comment]
Hi Quian-Han. The issue is you are supposed to substitute ${API_KEY} and  ${SHA256} by actual values. So eventually your url should look like apikey=123456&sha256=00008E0B8F27CFCDFA2A73A45A4450B0D5255F63C8B5AE407AEEF0DEA9842174
I have used 123456 as sample api key, you should use the one provided by androzoo.

**Comment by kallix** [comment]
Issue totally unrelated to this repo. User misunderstood the androzoo documentation. 
Sorry for the noise... (we really have to update our doc keeping in mind that "youngsters" don't understand standard Bash syntax anymore :-) )

**Comment by Qian-Han** [comment]
Thanks a lot for the explanation!
